### ISSUE TITLE
No live info available through api

### ISSUE THREAD

**Issue by legeiger** [niklaskappler/MMM-vvsDeparture#3]
The currently used api doesn't provide any live info anymore:

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/42470274/49334401-7683fa00-f5d5-11e8-9727-88db21eb971c.png)

![image](https://user-images.githubusercontent.com/42470274/49334392-52281d80-f5d5-11e8-9717-7090109f5711.png) </details>

I found a other api url directly from the vvs in https://github.com/wienand/fahrplanauskunft-vvs/blob/master/fahrplanauskunft-vvs.py: 
`http://mobile.vvs.de/jqm/controller/XSLT_DM_REQUEST?limit=20&mode=direct&type_dm=stop&useRealtime=1&outputFormat=JSON&name_dm=`

Maybe this is a easy fix? It also responds with a json file...

**Comment by niklaskappler** [comment]
Hejsan, yes you are right. The api provides since a few week no live data. VVS is also shutting down version 1 of their api so an update ist really necessary (see #4).  I'm planning to update to the official VVS api, which are used by the App and their website. Unfortunately by changing the api the work is not done. There also some work had to be done for finding the correct station Id and and parsing the response. 

I'm planning to work on the module over the christmas days. Or if somebody like to work on it in the mean time, PR are welcome.

**Comment by niklaskappler** [comment]
Live data now working again.(See [v1.2](https://github.com/niklaskappler/MMM-vvsDeparture/tree/v1.2))
